### ISSUE TITLE
id uses Date & Random

### ISSUE THREAD

**Issue by tsuckow** [mdp/pitboss#2]
The id is generated with the current time and a random number. This seems to be rather unnecessary, the id could be generated with an incrementing static variable. Then you NEVER have to worry about the random number generator creating the same number and don't incur cost from retrieving the time and a random number.

**Comment by mdp** [comment]
Closing this out as there are better, more maintained alternatives - [vm2](https://github.com/patriksimek/vm2#readme) in particular
